### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by TheAmityD** [GeniusXanthron/kitchen-catastrophe-website#2]
**Due date**: 1 June 2022, 12:00 AM

To-Do:

- [ ] Make simple login and logout with SQL
- [ ] Make administrators' page
- [ ] Sprinkle some JavaScript
- [ ] Somehow have the ability for users to upload pictures (and search and select details) (insert, edit and delete also)
- [ ] Make all pages compatible with mobile devices (optional)

**Comment by TheAmityD** [comment]
Will do the second one during prep time, I guess
